### ISSUE TITLE
Unnecessary macros

### ISSUE THREAD

**Issue by purpleposeidon** [ZerothLaw/prattle-rs#1]
The macros aren't pulling their weight. Instead you could define a `pub struct TokenList<Vec<String>>` and change the methods to accept an `impl Into<TokenList>` param, and `impl From<…> for TokenList` with `String`, `Vec<&str>`, `&[String]`, etc. In this way you can also avoid `"blah".to_string()`.

**Comment by ZerothLaw** [comment]
Added IntoIterator and Into<T> trait bounds to some of the interfaces, which makes them way more ergonomic to use.
