### ISSUE TITLE
Overkill bounds

### ISSUE THREAD

**Issue by purpleposeidon** [ZerothLaw/prattle-rs#2]
Regarding https://docs.rs/prattle/0.1.2/src/prattle/parser.rs.html#53

`Eq: PartialEq`, so you don't need both.

If you really need all those bounds, you could do something like
```rust
trait Token: Debug + Eq BlahBlah {}
impl<X> Token for X where X: Debug + Eq + BlahBlah {}

struct Parser<T: Token>
```

and save wear & tear on the clipboard.

**Comment by ZerothLaw** [comment]
Thanks! Looked up the various traits, and saw Ord is Eq + Partial Ord. Doing that plus the Token marker trait and blanket impl reduced compile times by about 20%, which is both surprising and not surprising when I think about it. 

The feedback is greatly appreciated!

**Comment by ZerothLaw** [comment]
Here's the pull request, if you wouldn't mind looking this over? https://github.com/ZerothLaw/prattle-rs/pull/3

**Comment by ZerothLaw** [comment]
Closed as I believe I've resolved the issues with my latest commits on the bounds branch.
